server:
  port: 9001
  error:
    include-message: always
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/nikodemo
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    database: postgresql
    defer-datasource-initialization: true  #since spring boot 2.5.0 required for initialization
  sql:
    init:
      mode: always
      data-locations: classpath:db/init-data.sql
  security:
    user:
      name: user
      password: user
